{
 "title": "Grafana Dashboard for Veeam ONE Node Exporter",
 "description": "Grafana Dashboard for Veeam ONE Node Exporter (Unofficial)",
 "tags": [
  "veeam",
  "veeam exporter",
  "veeam node exporter",
  "veeam metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backupserver",
    "label": "Backup Server",
    "query": {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vone_exporter\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"serv\" or r[\"role\"] == \"vbm_srv\")\r\n  |> keep(columns: [\"host\"])\r\n  |> distinct(column: \"host\")\r\n  |> group()"
    }
   },
   {
    "name": "proxyserver",
    "label": "Proxy Server",
    "query": {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vone_exporter\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"prx\" or r[\"role\"] == \"vbm_prx\")\r\n  |> keep(columns: [\"host\"])\r\n  |> distinct(column: \"host\")\r\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  { "title": "Veeam ONE Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\nok =\r\n  array.from(rows: [{\r\n    _time: now(),\r\n    host: \"\",\r\n    message: \"No errors occurred in the selected period\",\r\n    _value: \"No errors occurred in the selected period\",\r\n    status: 0\r\n  }])\r\n\r\nerr =\r\n  from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n    |> filter(fn: (r) => r._field == \"vone_exporter_last_scrape_error_info\")\r\n    |> filter(fn: (r) => exists r.message and r.message != \"\" and r.message != \"none\")\r\n    |> keep(columns: [\"_time\",\"message\",\"host\"])\r\n    |> sort(columns: [\"_time\"], desc: true)\r\n    |> limit(n: 1)\r\n    |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        host: r.host,\r\n        message: r.message,\r\n        _value: string(v: r._time) + \" - \" + r.message,   // <-- time + message\r\n        status: 1\r\n    }))\r\n\r\nunion(tables: [err, ok])\r\n  |> sort(columns: [\"status\",\"_time\"], desc: true)\r\n  |> limit(n: 1)\r\n  |> keep(columns: [\"_time\",\"host\",\"message\",\"_value\"])\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Node Exporter Status",
   "type": "stat",
   "description": "Veeam ONE Node Exporter Status",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\r\n\r\nbaseline =\r\n  array.from(rows: [{_time: now(), _value: 0}])\r\n\r\npresent =\r\n  from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n    |> filter(fn: (r) => r._field == \"vone_exporter_up\")\r\n    // |> filter(fn: (r) => r.voneserver =~ /${veeamoneserver:regex}/)\r\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n    |> last()\r\n    |> limit(n: 1)\r\n    |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n\r\nunion(tables: [baseline, present])\r\n  |> max(column: \"_value\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Veeam ONE - CPU Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_veeam_one_server_cpu_usage_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"voneserver\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"voneserver\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Veeam ONE - RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_veeam_one_server_memory_usage_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"voneserver\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"voneserver\"])\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_veeam_one_server_memory_pressure_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"voneserver\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"voneserver\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Latest Node Scrape Success",
   "type": "stat",
   "description": "Latest Node Scrape Success",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_last_scrape_success_seconds\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Veeam Backup Servers Analytics (Includes VBR & VB365)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Backup Server - CPU Usage - $backupserver",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vone_exporter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vone_exporter_cpu_usage_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${backupserver:regex}/) \r\n  |> filter(fn: (r) => r[\"role\"] == \"serv\" or r[\"role\"] == \"vbm_srv\") \r\n  |> group(columns: [\"_measurement\", \"_field\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Backup Server - RAM Usage - $backupserver",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_memory_used_bytes\" or r._field == \"vone_exporter_memory_available_bytes\")\r\n  |> filter(fn: (r) => r.role == \"serv\" or r.role == \"vbm_srv\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${backupserver:regex}/) \r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      // consumed% = used / (used + available) * 100\r\n      _value: if exists r.vone_exporter_memory_used_bytes and exists r.vone_exporter_memory_available_bytes and\r\n                    (float(v: r.vone_exporter_memory_used_bytes) + float(v: r.vone_exporter_memory_available_bytes)) > 0.0\r\n              then float(v: r.vone_exporter_memory_used_bytes) /\r\n                   (float(v: r.vone_exporter_memory_used_bytes) + float(v: r.vone_exporter_memory_available_bytes)) * 100.0\r\n              else 0.0,\r\n      host: r.host,\r\n      role: r.role\r\n  }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"host\",\"role\"])\r\n"
    }
   ]
  },
  {
   "title": "Backup Server - Disk Usage - $backupserver",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_disk_bytes_per_sec\")\r\n  |> filter(fn: (r) => r.role == \"serv\" or r.role == \"vbm_srv\")\r\n  |> filter(fn: (r) => exists r.host and r.host =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => exists r.disk and r.disk != \"\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"_value\",\"host\",\"disk\",\"role\"])\r\n  |> group(columns: [\"host\",\"disk\"])\r\n"
    }
   ]
  },
  {
   "title": "Backup Server - Network Usage - Traffic Sent - $backupserver",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_net_bytes_sent_per_sec\")\r\n  |> filter(fn: (r) => r.role == \"serv\" or r.role == \"vbm_srv\")\r\n  |> filter(fn: (r) => exists r.host and r.host =~ /${backupserver:regex}/)\r\n  |> toFloat()\r\n  |> group(columns: [\"host\",\"role\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"tx B/s\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_net_bytes_received_per_sec\")\r\n  |> filter(fn: (r) => r.role == \"serv\" or r.role == \"vbm_srv\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${backupserver:regex}/)\r\n  |> toFloat()\r\n  |> group(columns: [\"host\",\"role\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"rx B/s\")"
    }
   ]
  },
  { "title": "Veeam Backup Proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Backup Proxies - CPU Usage - $proxyserver",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vone_exporter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vone_exporter_cpu_usage_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${proxyserver:regex}/)\r\n  |> filter(fn: (r) => r[\"role\"] == \"prx\" or r[\"role\"] == \"vbm_prx\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Backup Proxies - RAM Usage - $server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_memory_used_bytes\" or r._field == \"vone_exporter_memory_available_bytes\")\r\n  |> filter(fn: (r) => r.role == \"prx\" or r.role == \"vbm_prx\")\r\n  |> filter(fn: (r) => exists r.host and r.host =~ /${proxyserver:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      // consumed% = used / (used + available) * 100\r\n      _value: if exists r.vone_exporter_memory_used_bytes and exists r.vone_exporter_memory_available_bytes and\r\n                    (float(v: r.vone_exporter_memory_used_bytes) + float(v: r.vone_exporter_memory_available_bytes)) > 0.0\r\n              then float(v: r.vone_exporter_memory_used_bytes) /\r\n                   (float(v: r.vone_exporter_memory_used_bytes) + float(v: r.vone_exporter_memory_available_bytes)) * 100.0\r\n              else 0.0,\r\n      host: r.host,\r\n      role: r.role\r\n  }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"host\",\"role\"])\r\n"
    }
   ]
  },
  {
   "title": "Backup Server - Disk Usage - $proxyserver",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_disk_bytes_per_sec\")\r\n  |> filter(fn: (r) => r.role == \"prx\" or r.role == \"vbm_prx\")\r\n  |> filter(fn: (r) => exists r.host and r.host =~ /${proxyserver:regex}/)\r\n  |> filter(fn: (r) => exists r.disk and r.disk != \"\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"_value\",\"host\",\"disk\",\"role\"])\r\n  |> group(columns: [\"host\",\"disk\"])\r\n"
    }
   ]
  },
  {
   "title": "Backup Proxies - Network Usage - Traffic Sent - $proxyserver",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_net_bytes_sent_per_sec\")\r\n  |> filter(fn: (r) => r.role == \"prx\" or r.role == \"vbm_prx\")\r\n  |> filter(fn: (r) => exists r.host and r.host =~ /${proxyserver:regex}/)\r\n  |> toFloat()\r\n  |> group(columns: [\"host\",\"role\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"tx B/s\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vone_exporter\")\r\n  |> filter(fn: (r) => r._field == \"vone_exporter_net_bytes_received_per_sec\")\r\n  |> filter(fn: (r) => r.role == \"serv\" or r.role == \"vbm_srv\")\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${proxyserver:regex}/)\r\n  |> toFloat()\r\n  |> group(columns: [\"host\",\"role\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"rx B/s\")"
    }
   ]
  }
 ]
}