name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore .\VoneExporter.csproj

      - name: Publish win-x64 self contained single file
        run: |
          dotnet publish .\VoneExporter.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -o .\out\win-x64

      - name: Include example config
        shell: pwsh
        run: |
          Copy-Item -Path .\appsettings.example.json -Destination .\out\win-x64\appsettings.json -Force

      - name: Package ZIP
        shell: pwsh
        run: |
          $version = "${{ github.ref }}".Replace("refs/tags/", "")
          $zipName = "voneexporter-$version-win-x64.zip"
          Compress-Archive -Path .\out\win-x64\* -DestinationPath $zipName -Force
          Get-FileHash $zipName -Algorithm SHA256 | ForEach-Object {
            "{0}  {1}" -f $_.Hash.ToLower(), $zipName | Out-File "$zipName.sha256" -Encoding ascii
          }

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          make_latest: true
          files: |
            voneexporter-*-win-x64.zip
            voneexporter-*-win-x64.zip.sha256
